name = "bv-pages"
pages_build_output_dir = "dist"
compatibility_date = "2024-06-20"

[vars]
STR_MESSAGE = "Hello, From Wrangler!"

# [[d1_databases]]
# binding = "DB"
# database_name = "appdb"
# database_id = "<database-id>"

# [[kv_namespaces]]
# binding = "KV"
# id = "<namespace-id>"

[ai]
binding = "AI"